
---
manager:
  max_workers: 10

providers:

  zones:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 300
    enforce_order: true

  cloudflare:
    # class: octodns.provider.cloudflare.CloudflareProvider
    class: octodns_cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN

processors:

  exclude-names:
    class: octodns.processor.filter.NameRejectlistFilter
    rejectlist:
      # exact string match
      # - www
      # contains/substring match
      # - /substring/
      # regex pattern match
      # - /some-pattern-\\d\\+/
      # regex - anchored so has to match start to end
      # - /^start-.+-end$/
      #
      # - callisto
      - /dynamic-/

  # include-names:
  #   class: octodns.processor.filter.NameAllowlistFilter
  #   allowlist:



zones:

  grumpydude.com.:
    sources:
      - zones
    processors:
      - exclude-names
    targets:
      - cloudflare

  grumpydudette.com.:
    sources:
      - zones
    targets:
      - cloudflare

  kcrew.net.:
    sources:
      - zones
    targets:
      - cloudflare

