on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: octoDNS Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          refs: main

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4

      - name: Run octoDNS sync
        run: octodns-sync --config-file=./config.yaml --doit
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
